### ISSUE TITLE
Add an option to stop on error?

### ISSUE THREAD

**Issue by kokarn** [jwilsson/deployy-mcdeployface#2]
I've been thinking if we should add an option to stop on error.

In some cases it might be pretty usefull, such as when `npm install --production` fails, do we really want to run our migrate scripts or stuff like that?

**Comment by jwilsson** [comment]
Sounds good!

I think adding it globally would make the most sense, so it applies to all repos.

**Comment by kokarn** [comment]
So it never proceeds if the previous task failed?

**Comment by jwilsson** [comment]
Exactly!

**Comment by kokarn** [comment]
Do we know of any services that might return a non-zero code when succeeding? I know grunt's had some issues with that and I think some services return 1 for warnings.

**Comment by jwilsson** [comment]
Hmm, I think that might be out of scope and up to each service/process to exit properly.

Node's `child_process` will treat any exit code other than `0` as a error as well (https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) which will be what we're utilizing.

**Comment by kokarn** [comment]
Agreed. Makes it maintainable and limits our scope in a good way :+1:

**Comment by kokarn** [comment]
UPDATE: Right now it actually seems to stop on error. Easy way to test is this config. `npm install`
 is never run.

``` json
{
        "host": "example.com",
        "port": 1234,
        "repos": {
                "kokbot": {
                        "path": "/path/to/folder/without/git",
                        "commands": [
                                "git pull",
                                "npm install"
                        ]
                }
        }
}
```
